# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/ultra96.xdc

# Block Designs: bd/sensors96b/sensors96b.bd
# Block Designs: The module: 'sensors96b' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: bd/sensors96b/ip/sensors96b_axi_uart16550_0_0/sensors96b_axi_uart16550_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sensors96b_axi_uart16550_0_0 || ORIG_REF_NAME==sensors96b_axi_uart16550_0_0} -quiet] -quiet

# IP: bd/sensors96b/ip/sensors96b_axi_uart16550_1_0/sensors96b_axi_uart16550_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sensors96b_axi_uart16550_1_0 || ORIG_REF_NAME==sensors96b_axi_uart16550_1_0} -quiet] -quiet

# IP: bd/sensors96b/ip/sensors96b_proc_sys_reset_0_0/sensors96b_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sensors96b_proc_sys_reset_0_0 || ORIG_REF_NAME==sensors96b_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/sensors96b/ip/sensors96b_xbar_0/sensors96b_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sensors96b_xbar_0 || ORIG_REF_NAME==sensors96b_xbar_0} -quiet] -quiet

# IP: bd/sensors96b/ip/sensors96b_ps8_0_axi_periph_0/sensors96b_ps8_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sensors96b_ps8_0_axi_periph_0 || ORIG_REF_NAME==sensors96b_ps8_0_axi_periph_0} -quiet] -quiet

# IP: bd/sensors96b/ip/sensors96b_xlconcat_0_0/sensors96b_xlconcat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sensors96b_xlconcat_0_0 || ORIG_REF_NAME==sensors96b_xlconcat_0_0} -quiet] -quiet

# IP: bd/sensors96b/ip/sensors96b_xlconcat_1_0/sensors96b_xlconcat_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sensors96b_xlconcat_1_0 || ORIG_REF_NAME==sensors96b_xlconcat_1_0} -quiet] -quiet

# IP: bd/sensors96b/ip/sensors96b_xlconstant_0_0/sensors96b_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sensors96b_xlconstant_0_0 || ORIG_REF_NAME==sensors96b_xlconstant_0_0} -quiet] -quiet

# IP: bd/sensors96b/ip/sensors96b_zynq_ultra_ps_e_0_0/sensors96b_zynq_ultra_ps_e_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sensors96b_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==sensors96b_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/sensors96b/ip/sensors96b_simple_0_0/sensors96b_simple_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sensors96b_simple_0_0 || ORIG_REF_NAME==sensors96b_simple_0_0} -quiet] -quiet

# IP: bd/sensors96b/ip/sensors96b_auto_pc_0/sensors96b_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sensors96b_auto_pc_0 || ORIG_REF_NAME==sensors96b_auto_pc_0} -quiet] -quiet

# XDC: C:/Users/zunmun/Documents/Stuff/Github/WORK/Bumblebee/ultra96_vivado_tests/PYNQ/gpiok_blink/gpiok_blink.gen/sources_1/bd/sensors96b/sensors96b_ooc.xdc
